<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Marketplace.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marketplace.Application\Marketplace.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.*" />
    <PackageReference Include="Google.Apis.Auth" Version="1.*" />
    <PackageReference Include="AWSSDK.S3" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Seed\product-templates.json" LogicalName="product-templates.json" />
  </ItemGroup>
</Project>
